# Generated by Django 3.0.1 on 2020-01-05 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_auto_20200105_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 5, 9, 50, 26, 812312)),
        ),
    ]
