# Generated by Django 3.0.1 on 2020-01-05 03:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('floors', models.DecimalField(decimal_places=2, max_digits=2)),
                ('bathroom', models.IntegerField()),
                ('garage', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='photo%y/%m/%d')),
                ('road_feet', models.DecimalField(decimal_places=2, max_digits=2)),
                ('photo_second', models.ImageField(blank=True, upload_to='photo/%y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='merchants.Merchant')),
            ],
        ),
    ]
